#!/usr/bin/env node
// Single source of truth -> every client's plugin files.
//
// Edit only:
//   src/config.json      shared constants (name, version, MCP endpoint, ...)
//   src/skill.body.md    the agent instructions, written once
//
// Everything this script writes is generated. Do not hand-edit the outputs.
// Run `node scripts/generate.mjs` to regenerate, or `--check` to verify the
// committed files match the sources (used in CI / pre-commit).

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

const config = JSON.parse(read("src/config.json"));
const skillBody = read("src/skill.body.md");

const json = (obj) => JSON.stringify(obj, null, 2) + "\n";

// --- skill files -----------------------------------------------------------

const rootSkill = `> Paste-anywhere copy of the Cofound agent skill, for MCP clients without a
> plugin bundle (Cline, Continue, ChatGPT, Codex stdio fallback): drop the body
> below into your system prompt or AGENTS.md. Generated from \`src/skill.body.md\`
> by \`scripts/generate.mjs\`; do not edit this file by hand.

${skillBody}`;

const pluginSkill = `---
name: ${config.skill.name}
description: ${config.skill.description}
---

${skillBody}`;

// --- MCP server definitions (one endpoint, three client dialects) ----------

const claudeMcp = {
  cofound: {
    type: "http",
    url: config.mcp.url,
    headers: {
      Accept: config.mcp.acceptHeader,
    },
  },
};

const cursorMcp = {
  cofound: {
    url: config.mcp.url,
    headers: {
      Accept: config.mcp.acceptHeader,
    },
  },
};

const codexMcpFile = {
  mcp_servers: {
    cofound: {
      url: config.mcp.url,
      bearer_token_env_var: config.mcp.tokenEnvVar,
      http_headers: { Accept: config.mcp.acceptHeader },
    },
  },
};

// --- manifests -------------------------------------------------------------

const claudePlugin = {
  $schema: "https://json.schemastore.org/claude-code-plugin.json",
  name: config.name,
  version: config.version,
  description: config.description,
  author: config.author,
  homepage: config.homepage,
  repository: config.repository,
  license: config.license,
  keywords: config.keywords,
  mcpServers: claudeMcp,
};

const claudeMarketplace = {
  $schema: "https://json.schemastore.org/claude-code-marketplace.json",
  name: config.marketplace.name,
  owner: config.marketplace.owner,
  plugins: [
    {
      name: config.name,
      source: ".",
      description: config.marketplaceDescription,
      version: config.version,
      homepage: config.homepage,
      license: config.license,
      keywords: config.keywords,
    },
  ],
};

const cursorPlugin = {
  name: config.name,
  version: config.version,
  description: config.description,
  author: { name: config.author.name },
  homepage: config.homepage,
  repository: config.repository,
  license: config.license,
  keywords: config.keywords,
  skills: "./skills/",
  mcpServers: cursorMcp,
};

const cursorMarketplace = {
  name: config.marketplace.name,
  owner: { name: config.marketplace.owner.name },
  plugins: [
    {
      name: config.name,
      source: ".",
      description: config.marketplaceDescription,
      version: config.version,
      homepage: config.homepage,
      license: config.license,
      keywords: config.keywords,
    },
  ],
};

const codexPlugin = {
  name: config.name,
  version: config.version,
  description: config.description,
  author: config.author,
  homepage: config.homepage,
  repository: config.repository,
  license: config.license,
  keywords: config.keywords,
  skills: "./skills/",
  mcpServers: "./mcp.codex.json",
  interface: {
    displayName: config.displayName,
    shortDescription: config.shortDescription,
    longDescription: config.description,
    developerName: config.author.name,
    category: config.category,
    capabilities: ["Interactive", "Write"],
    websiteURL: config.homepage,
  },
};

// Cursor one-click install deeplink. config = base64(JSON.stringify(server)).
const cursorDeeplinkConfig = {
  url: config.mcp.url,
  headers: {
    Accept: config.mcp.acceptHeader,
  },
};
const cursorDeeplink =
  `cursor://anysphere.cursor-deeplink/mcp/install?name=${config.mcp.serverName}` +
  `&config=${Buffer.from(JSON.stringify(cursorDeeplinkConfig)).toString("base64")}`;

const cursorDeeplinkDoc = `# Add Cofound to Cursor (one-click)

Generated by \`scripts/generate.mjs\`; do not edit by hand.

Click to add Cofound to Cursor, then sign in through your browser:

[Add Cofound to Cursor](${cursorDeeplink})

If your browser drops the link, paste it into the address bar:

\`\`\`
${cursorDeeplink}
\`\`\`
`;

// Codex marketplace catalog. Schema mirrors openai/plugins'
// .agents/plugins/marketplace.json. The plugin lives at the repo root (the same
// root Claude and Cursor use), so the local source path is ".".
const codexMarketplace = {
  name: config.marketplace.name,
  interface: { displayName: config.marketplace.owner.name },
  plugins: [
    {
      name: config.name,
      source: { source: "local", path: "." },
      // authentication: ON_INSTALL | ON_USE. Codex uses the static bearer token
      // (no MCP OAuth), so the token rides every request and auth is on use.
      policy: { installation: "AVAILABLE", authentication: "ON_USE" },
      category: config.category,
    },
  ],
};

// --- emit ------------------------------------------------------------------

const outputs = {
  "SKILL.md": rootSkill,
  "skills/cofound/SKILL.md": pluginSkill,
  ".claude-plugin/plugin.json": json(claudePlugin),
  ".claude-plugin/marketplace.json": json(claudeMarketplace),
  ".cursor-plugin/plugin.json": json(cursorPlugin),
  ".cursor-plugin/marketplace.json": json(cursorMarketplace),
  ".codex-plugin/plugin.json": json(codexPlugin),
  "mcp.codex.json": json(codexMcpFile),
  ".agents/plugins/marketplace.json": json(codexMarketplace),
  "docs/cursor-deeplink.md": cursorDeeplinkDoc,
};

const check = process.argv.includes("--check");
const drift = [];

for (const [rel, content] of Object.entries(outputs)) {
  const abs = join(root, rel);
  if (check) {
    const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
    if (current !== content) drift.push(rel);
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    console.log(`wrote ${rel}`);
  }
}

if (check) {
  if (drift.length) {
    console.error("Out of date, run `node scripts/generate.mjs`:");
    for (const f of drift) console.error(`  ${f}`);
    process.exit(1);
  }
  console.log(`All ${Object.keys(outputs).length} generated files are up to date.`);
}
